# Generated by Django 4.0.2 on 2022-03-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('local', models.CharField(max_length=100)),
                ('horario', models.DateTimeField()),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
