# Generated by Django 4.0.2 on 2022-04-11 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('defesa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defesa',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario'),
        ),
    ]
