# Generated by Django 4.0.2 on 2022-03-29 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('secao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, unique=True)),
                ('conteudo', models.TextField()),
                ('ordem', models.IntegerField(unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('secao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='secao.secao')),
                ('usuarios', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario')),
            ],
        ),
    ]
