# Generated by Django 4.0.3 on 2022-03-29 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('subsecao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsecao',
            name='usuarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario'),
        ),
    ]
