# Generated by Django 4.0.3 on 2022-03-29 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secao', '0001_initial'),
        ('subsecao', '0002_alter_subsecao_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsecao',
            name='secao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secao.secao'),
        ),
    ]
