# Generated by Django 4.0.2 on 2022-03-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsecao', '0003_alter_subsecao_secao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsecao',
            name='ordem',
            field=models.IntegerField(),
        ),
    ]
