
icons = {
        'Android' : 'fab fa-android',
        'Apple' : 'fab fa-apple',
        'Aranha' : 'fas fa-spider',
        'Ampulheta' : 'fas fa-hourglass-half',
        'Alinhado ao centro' : 'fas fa-align-center',
        'Alfinete' : 'fas fa-thumbtack',
        'Justificado' : 'fas fa-align-justify',
        'Alinhado à esquerda' : 'fas fa-align-left',
        'Alinhado à direita' : 'fas fa-align-right',
        'Âncora' : 'fas fa-anchor',
        'Asterísco' : 'fas fa-asterisk',
        'Arroba' : 'fas fa-at',
        'Avião' : 'fas fa-plane',
        'Bandeira' : 'fas fa-flag',
        'Balança Justiça' : 'fas fa-balance-scale',
        'Balão de comentário' : 'far fa-comment',
        'Bateria' : 'fas fa-battery-three-quarters',
        'Bíblia' : 'fas fa-bible',
        'Binóculo' : 'fas fa-binoculars',
        'Bolo de aniversário' : 'fas fa-birthday-cake',
        'Bitcoin' : 'fab fa-bitcoin',
        'Bloco de notas' : 'fas fa-sticky-note',
        'Bluetooth' : 'fab fa-bluetooth',
        'Bomba' : 'fas fa-bomb',
        'Cachorro' : 'fas fa-dog',
        'Cadeado' : 'fas fa-lock',
        'Cadeira de rodas' : 'fab fa-accessible-icon',
        'Caixa registradora': 'fas fa-cash-register',
        'Calculadora' : 'fas fa-calculator',
        'Calendário' : 'far fa-calendar-alt',
        'Caneta' : 'fas fa-marker',
        'Câmera' : 'fas fa-camera',
        'Caminhão' : 'fas fa-truck',
        'Capa de livro com pessoa' : 'fas fa-address-book',
        'Cartão com pessoa' : 'fas fa-address-card',
        'Carro' : 'fas fa-car',
        'Cartão SD' : 'fas fa-sd-card',
        'Cavalo' : 'fas fa-horse',
        'Carrinho de bebê' : 'fas fa-baby-carriage',
        'Carrinho de compras' : 'fas fa-shopping-cart',
        'Cérebro' : 'fas fa-brain',
        'Casa' : 'fas fa-home',
        'Chapéu de formatura' : 'fas fa-graduation-cap',
        'Chave' : 'fas fa-key',
        'Chuveiro' : 'fas fa-shower',
        'Cifrão' : 'fas fa-dollar-sign',
        'Clipe' : 'fas fa-paperclip',
        'Código de Barras' : 'fas fa-barcode',
        'Compartilhar' : 'fas fa-share-alt-square',
        'Curativo' : 'fas fa-band-aid',
        'Dados' : 'fas fa-dice',
        'Dente' : 'fas fa-tooth',
        'Diagrama' : 'fas fa-sitemap',
        'Documento': 'fas fa-file-alt',
        'Escudo': 'fas fa-shield-alt',
        'Estrela' : 'fas fa-star',
        'Facebook' : 'fab fa-facebook-square',
        'Feminino' : 'fas fa-female',
        'Ferramentas' : 'fas fa-tools',
        'Floco de neve' : 'fas fa-snowflake',
        'Fone de ouvido' : 'fas fa-headphones',
        'Funil' : 'fas fa-filter',
        'Engrenagem' : 'fas fa-cog',
        'Envelope': 'fas fa-envelope',
        'Estetoscópio' : 'fas fa-stethoscope',
        'Garfo e faca' : 'fas fa-utensils',
        'Gato' : 'fas fa-cat',
        'Globo terrestre' : 'fas fa-globe-americas',
        'Google' : 'fab fa-google',
        'Google Drive' : 'fab fa-google-drive',
        'Google Play Store' : 'fab fa-google-play',
        'Gota' : 'fas fa-tint',
        'Guarda-chuva': 'fas fa-umbrella',
        'Hashtag' : 'fas fa-hashtag',
        'Helicóptero' : 'fas fa-helicopter',
        'Hipopótamo' : 'fas fa-hippo',
        'HD' : 'fas fa-hdd',
        'Ícone de informação' : 'fas fa-info-circle',
        'Ímã' : 'fas fa-magnet',
        'Instagram' : 'fab fa-instagram',
        'Impressora' : 'fas fa-print',
        'Lâmpada' : 'fas fa-lightbulb',
        'Lápis' : 'fas fa-pencil-alt',
        'Linguagem de sinais' : 'fas fa-sign-language',
        'Linkedin' : 'fab fa-linkedin',
        'Livro fechado' : 'fas fa-book',
        'Livro aberto' : 'fas fa-book-open',
        'Lixeira' : 'fas fa-trash',
        'Lua' : 'fas fa-moon',
        'Lupa' : 'fas fa-search',
        'Martelo' : 'fas fa-hammer',
        'Mapa' : 'fas fa-map-marked-alt',
        'Masculino' : 'fas fa-male',
        'Medalha': 'fas fa-medal',
        'Messenger' : 'fab fa-facebook-messenger',
        'Microfone' : 'fas fa-microphone-alt',
        'Monitor de computador' : 'fas fa-desktop',
        'Nota musical' : 'fas fa-music',
        'Notebook' : 'fas fa-laptop',
        'Óculos' : 'fas fa-glasses',
        'Ônibus' : 'fas fa-bus-alt',
        'Osso' : 'fas fa-bone',
        'Passáro' : 'fas fa-dove',
        'Pasta' : 'fas fa-folder-open',
        'Pena' : 'fas fa-feather-alt',
        'Peixe' : 'fas fa-fish',
        'Pincel' : 'fas fa-paint-brush',
        'Pinterest' : 'fab fa-pinterest',
        'Pizza' : 'fas fa-pizza-slice',
        'Play' : 'fas fa-play-circle',
        'Prédio' : 'fas fa-building',
        'Proibido fumar' : 'fas fa-smoking-ban',
        'Raio' : 'fas fa-bolt',
        'Reciclagem' : 'fas fa-recycle',
        'Régua' : 'fas fa-ruler-horizontal',
        'Rôbo' : 'fas fa-robot',
        'Sapo' : 'fas fa-frog',
        'Sino' : 'fas fa-bell',
        'Sinal de internet' : 'fas fa-signal',
        'Snapchat' : 'fab fa-snapchat',
        'Skype' : 'fab fa-skype',
        'Steam' : 'fab fa-steam-square',
        'Tag' : 'fas fa-tag',
        'Teclado' : 'fas fa-keyboard',
        'Telefone' : 'fas fa-phone-alt',
        'Telegram': 'fab fa-telegram',
        'Termômetro' : 'fas fa-thermometer-quarter',
        'Tomada' : 'fas fa-plug',
        'Trello' : 'fab fa-trello',
        'Troféu' : 'fas fa-trophy',
        'Twitch' : 'fab fa-twitch',
        'Twitter' : 'fab fa-twitter',
        'Violão' : 'fas fa-guitar',
        'USB' : 'fab fa-usb',
        'Usuário' : 'fas fa-user-alt',
        'Usuário formatura' : 'fas fa-user-graduate',
        'Vaso sanitário' : 'fas fa-toilet',
        'Vídeo' : 'fas fa-video',
        'Vírus': 'fas fa-virus',
        'Volume desligado' : 'fas fa-volume-mute',
        'Volume ligado' : 'fas fa-volume-up',
        'Whatsapp' : 'fab fa-whatsapp',
        'Windows' : 'fab fa-windows',
        'Wi-Fi' : 'fas fa-rss',
        'Wikipedia' : 'fab fa-wikipedia-w',
        'Xícara' : 'fas fa-coffee',
        'Yin e Yang' : 'fas fa-yin-yang',
        'Youtube' : 'fab fa-youtube',
    }
