# Generated by Django 4.0.2 on 2022-03-23 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('previa', models.TextField()),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now=True)),
                ('img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.arquivo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario')),
            ],
        ),
    ]
