# Generated by Django 4.0.2 on 2022-04-04 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_arquivo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='tipo_arquivo',
        ),
    ]
