# Generated by Django 4.0.2 on 2022-03-23 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=100)),
                ('ordem', models.IntegerField()),
                ('ativada', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario')),
                ('usuarios', models.ManyToManyField(related_name='+', to='usuario.Usuario')),
            ],
        ),
    ]
