# Generated by Django 4.0.2 on 2022-04-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secao', '0002_alter_secao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secao',
            name='titulo',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
